## 2.1 Internal Sequencial Type

**Container Sequencial** \
list, tuple, collections.deque, these types can store different types data

**Flat Sequence** \
str, bytes, bytearray, memoryview, and array.array, these types can only store one type of data. 

**Mutable Sequence** \
list, bytearray, array.array, collections.deque, memoryview

**Sequence** \
tuple, str, bytes

## 2.2 List Comprehension (listcomps) & Generator Expression(genexps)

In [4]:
invoice = """
0.....6................................40...........52...55........\n
1909  Pimoroni PiBrella                       $17.50    3    $52.50\n
1489  6mm Tactile Switch x20                   $4.95    2     $9.90\n
1510  Panavise Jr.-PV-201                     $28.00    1    $28.00\n
1601  PiTFT Mini Kit 320x240                  $34.95    1    $34.95\n
"""

In [1]:
SKU = slice(6, 40)
DESCRIPTION = slice(6, 40) 
UNIT_PRICE = slice(40, 52)
QUANTITY = slice(52, 55)
ITEM_TOTAL = slice(55, None)

In [8]:
line_items = invoice.split('\n')
line_items

['',
 '0.....6................................40...........52...55........',
 '',
 '1909  Pimoroni PiBrella                       $17.50    3    $52.50',
 '',
 '1489  6mm Tactile Switch x20                   $4.95    2     $9.90',
 '',
 '1510  Panavise Jr.-PV-201                     $28.00    1    $28.00',
 '',
 '1601  PiTFT Mini Kit 320x240                  $34.95    1    $34.95',
 '',
 '']

In [9]:
line_items = invoice.split('\n')[2:]
line_items

['',
 '1909  Pimoroni PiBrella                       $17.50    3    $52.50',
 '',
 '1489  6mm Tactile Switch x20                   $4.95    2     $9.90',
 '',
 '1510  Panavise Jr.-PV-201                     $28.00    1    $28.00',
 '',
 '1601  PiTFT Mini Kit 320x240                  $34.95    1    $34.95',
 '',
 '']

In [10]:
for item in line_items:
    print(item[UNIT_PRICE], item[DESCRIPTION])

 
      $17.50 Pimoroni PiBrella                 
 
       $4.95 6mm Tactile Switch x20            
 
      $28.00 Panavise Jr.-PV-201               
 
      $34.95 PiTFT Mini Kit 320x240            
 
 


## Instance 2.7

In [1]:
# instance 2.7

fruits = ['grape', 'raspberry', 'apple', 'banana']
sorted(fruits)

['apple', 'banana', 'grape', 'raspberry']

In [2]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [3]:
sorted(fruits, reverse=True)

['raspberry', 'grape', 'banana', 'apple']

In [4]:
sorted(fruits, key=len)

['grape', 'apple', 'banana', 'raspberry']

In [5]:
sorted(fruits, key=len, reverse=True)

['raspberry', 'banana', 'grape', 'apple']

In [6]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [8]:
fruits.sort()
fruits

['apple', 'banana', 'grape', 'raspberry']

## Instance 2.8

In [11]:
# 2.8.1

import bisect

def grade(score, breakpoints=[60, 70, 80, 90], grades='FDCBA'):
    i = bisect.bisect(breakpoints, score)
    return grades[i]

[grade(score) for score in [33, 99, 77, 70, 89, 90, 100]]

['F', 'A', 'C', 'C', 'B', 'A', 'A']

In [12]:
# 2.8.2

import bisect
import random

SIZE = 7
random.seed(1729)
my_list = []
for i in range(SIZE):
    new_item = random.randrange(SIZE * 2)
    bisect.insort(my_list, new_item)
    print("%2d --> "%new_item, my_list)

10 -->  [10]
 0 -->  [0, 10]
 6 -->  [0, 6, 10]
 8 -->  [0, 6, 8, 10]
 7 -->  [0, 6, 7, 8, 10]
 2 -->  [0, 2, 6, 7, 8, 10]
10 -->  [0, 2, 6, 7, 8, 10, 10]


## 2.9 Instrance

In [19]:
#2.20

from array import array
from random import random

floats = array('d', (random() for i in range(10**7)))
print(floats[-1])
fp = open('floats.bin', 'wb+')
floats.tofile(fp)
fp.close()
floats2 = array('d')
fp = open('floats.bin', 'rb')
floats2.fromfile(fp, 10**7)
fp.close()
print(floats2[-1])
print(floats2 == floats)

0.9042053515838744
0.9042053515838744
True


In [24]:
#2.21
from array import array
import array

numbers = array.array('h', [-2, -1, 0, 1, 2])
memv = memoryview(numbers)
print(len(memv))
print(memv[0])
memv_oct = memv.cast('B')
print(memv_oct.tolist())
memv_oct[5] = 4
print(numbers)


5
-2
[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]
array('h', [-2, -1, 1024, 1, 2])


In [25]:
#2.22
import numpy
a = numpy.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [26]:
type(a)

numpy.ndarray

In [27]:
a.shape

(12,)

In [29]:
a.shape = 3,4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
a[2]

array([ 8,  9, 10, 11])

In [31]:
a[2,1]

9

In [32]:
a[:, 1]

array([1, 5, 9])

In [33]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [44]:
#2.23

from collections import deque
dq = deque(range(10), maxlen=10)
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
dq.rotate(3)
dq

deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6])

In [46]:
dq.rotate(-4)
dq

deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [47]:
dq.appendleft(-1)
dq

deque([-1, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
dq.extend([11,22,33])
dq

deque([3, 4, 5, 6, 7, 8, 9, 11, 22, 33])

In [50]:
dq.extendleft([10,20,30,40])
dq

deque([40, 30, 20, 10, 3, 4, 5, 6, 7, 8])